name: demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #  请求
  dio: ^3.0.9
  #常用工具类
  common_utils: ^1.2.1
  flustars: ^0.3.2
  #  轮播
  flutter_swiper: ^1.1.4
  #电话/打开网址/邮件/信息
  url_launcher: ^5.4.11
  #  下拉刷新
  flutter_easyrefresh: 2.1.1
  #  事件通讯
  event_bus: ^1.1.1
  #  弹框r
  fluttertoast: ^3.1.2
  #  选取图片
  image_picker: ^0.6.7+2
  #  图片剪裁
  image_cropper: ^1.2.3
  #  三级联动
  city_pickers: ^0.1.30
  #  汉化
  flutter_localizations:
    sdk: flutter
  #    三级联动
  flutter_picker: ^1.1.5
  #路由
  fluro: "^1.6.3"
  #  全局变量
  provider: ^4.1.3
  #  二维码识别
  flutter_qr_reader: ^1.0.3
  #  文本溢出
  expandable: ^4.1.3
  #  富文本
  flutter_html: ^1.0.0-pre.1
  #  预览图片
  photo_view: ^0.9.2
  date_format: ^1.0.8 #时间处理
  #加载动画
  flutter_spinkit: ^4.1.2+1
  #  权限申请
  permission_handler: ^5.0.1+1
  #  获取经纬度
  amap_location: ^0.2.0
  #  版本号
  package_info: ^0.4.0+2
  #下载路径
  path_provider: ^1.6.10
  #  安装
  install_plugin: ^2.0.1
  # 视频播放器器
  video_player: ^0.10.11+2
  chewie: ^0.9.10
#  瀑布流
  flutter_staggered_grid_view: ^0.3.2
#  极光推送
  jpush_flutter: 0.5.5
#  高德地图
  amap_all_fluttify: 0.15.1
#  数据库
  sqflite: ^1.3.0
#微信录音
  flutter_plugin_record: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
      - image/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
